### ISSUE TITLE
Slider in 'extend boost' pop-up window does not work

### ISSUE THREAD

**Issue by abowery** [environmentalomics/eos-portal#10]
The slider in the 'extend boost' pop-up window does not calculate the new length of time of the boost and the amount of credit that will be deducted.

**Comment by ghost** [comment]
Beginning work on this issue now.

**Comment by ghost** [comment]
Done.

**Comment by abowery** [comment]
This bug fix is not showing in the 'extend boost' pop-up window.

**Comment by ghost** [comment]
Fixed.
