### ISSUE TITLE
The RAM and CPU values in the portal do not show the actual values of the VM

### ISSUE THREAD

**Issue by abowery** [environmentalomics/eos-portal#35]
The RAM and CPU values in the portal do not show the actual values of the VM.

**Comment by tbooth** [comment]
The portal only knows the RAM and CPU values that it set itself, so I believe what you are seeing is a result of changing RAM or CPU directly in vCloud director.  Therefore this is not a bug but a design limitation.  If you find a way to make the portal show incorrect values where no manipulation in vCD was involved please re-open this issue.
TIM
