### ISSUE TITLE
When a server is in a boosting state or de-boosting state it is possible to boost or de-boost again

### ISSUE THREAD

**Issue by abowery** [environmentalomics/eos-portal#8]
When a server is in a boosting state or a de-boosting state, it is possible to select to boost or de-boost, overriding the current activity. There should be a 'cancel' button that cancels the current 'boosting' or 'de-boosting' and the 'boost' and 'de-boost' buttons for that server should be locked off.

**Comment by ghost** [comment]
Merged with "When a server is in a state of Pre_Deboosting the 'Extend Boost' button should either be disabled or not shown."

**Comment by tbooth** [comment]
Only the appropriate buttons are now shown.  Having an actual Cancel button does not make sense given our state machine implementation, but one can effectively revert the action.
